[refactor/cart] CartItem 변경에 따른 리팩토링
class071/gaboja pull request #54
Opened 2022-12-13 16:58 UTC by gnoesnooj

- cart에서 order로 주문 시, Cart에 담겨있는 product를 나타내는 CartItem에 대한 검증
   - 올바른 수량인지
   - 유효한 product가 맞는지

- 기존 ProductLine 대신 CartItem으로 변경, Cart와 연관관계 설정

2022-12-19 12:45 UTC, graygreat requested changes

2022-12-19 12:45 UTC, graygreat commented on src/main/java/com/daily/gaboja/cart/domain/Cart.java
>      @ElementCollection(fetch = FetchType.EAGER)
페치 타입을 EAGER로 사용하신 이유가 무엇인가요?
EAGER 외 어떠한 타입들이 있고 어떠한 특징이 있나요?

2022-12-19 12:45 UTC, graygreat commented on src/main/java/com/daily/gaboja/cart/domain/Cart.java
> +    public void changeProductLines(List<CartItem> items) {
프로덕트 라인을 변환한다라는 메소드명이 아래 내용에 적합한지 모르겠네요.
더 나은 메소드 명이 없을까요?

2022-12-19 12:45 UTC, graygreat commented on src/main/java/com/daily/gaboja/cart/dto/CartReadResponseDto.java
>      public CartReadResponseDto toDto(Cart cart) {
toDto와 of 메소드명의 차이에 대해 알아보고 말씀해주세요

2022-12-19 12:45 UTC, graygreat commented on src/main/java/com/daily/gaboja/cart/dto/CartUpdateRequestDto.java
> +    private List<CartItem> cartItems;
Null을 허용하는 이유가 있을까요?
Java에서 Null을 허용하게 되면 어떠한 장, 단점이 있나요?

2022-12-19 12:45 UTC, graygreat commented on src/main/java/com/daily/gaboja/cart/service/CartService.java
>          Cart cart = cartRepository.findById(cartUpdateRequestDto.getCartId()).orElseThrow(CartNotExistException::new);
한줄에 .은 하나로 하도록 해보세용

2022-12-19 12:45 UTC, graygreat commented on src/main/java/com/daily/gaboja/cart/service/CartService.java
>          Cart cart = cartRepository.findById(cartUpdateRequestDto.getCartId()).orElseThrow(CartNotExistException::new);
해당 서비스에서 예외가 발생하면 어떻게 되나요?

2022-12-19 12:45 UTC, graygreat commented on src/main/java/com/daily/gaboja/cart/service/CartService.java
>          CartReadResponseDto cartReadResponseDto = new CartReadResponseDto();
다음과 같은 방법으로 객체를 생성하지 않고 객체를 만들 수 있는 패턴을 찾아보고 알려주세요.
적용까지!

2022-12-19 12:45 UTC, graygreat commented on src/main/java/com/daily/gaboja/order/service/OrderService.java
> +    private final ProductValidator productValidator;
값에 대한 검증을 service에서 하는 이유는 무엇일까요?
서비스에 검증, 컨트롤러에서 검증은 어떻게 구분할 수 있나요?

2022-12-19 12:45 UTC, graygreat commented on src/main/java/com/daily/gaboja/order/service/OrderService.java
> +        Cart cart = cartRepository.findById(orderRequestDto.getCartId()).orElseThrow(CartNotExistException::new);
카트를 조회하는 과정에서 반복되는 코드들이 있는데 줄여보세요

2022-12-19 12:45 UTC, graygreat commented on src/main/java/com/daily/gaboja/order/service/OrderService.java
>          Cart cart = cartRepository.findById(orderRequestDto.getCartId()).orElseThrow(CartNotExistException::new);
해당 로직이 실행되기 전에 값을 저장하는 로직이 있다고 가정해봐요.
이 로직에서 예외가 발생한다면 어떠한 문제가 생길까요?

2022-12-19 12:59 UTC, gnoesnooj commented on src/main/java/com/daily/gaboja/cart/domain/Cart.java
> +    public void changeProductLines(List<CartItem> items) {
productline이 수정되었는데 그걸 생각못하고 수정못했네요

장바구니의 물품내역들을 수정한다라는 의미를 담고싶어서 update 혹은 changeCartItems 로 작성해주었는데 updateCartItems가 더 좋은 메소드명이 될까요 ?

2022-12-19 13:03 UTC, gnoesnooj commented on src/main/java/com/daily/gaboja/cart/domain/Cart.java
>      @ElementCollection(fetch = FetchType.EAGER)
Eager 로 해줬던 이유는 Cart를 조회시에 Cart 장바구니 안에 담겨있는 물품내역들을 바로 가져와야한다고 생각해서 Eager 로 구현해주었습니다. 

Eager 외에는 알고 있던건 lazy 고, eager 가 가지고있는 n+1 과 같은단점들을 보완해주기 위해 lazy 를 적용한다고 알고 있습니다.

2022-12-19 13:04 UTC, gnoesnooj commented on src/main/java/com/daily/gaboja/cart/dto/CartUpdateRequestDto.java
> +    private List<CartItem> cartItems;
유저가 생성될 때 자연적으로 장바구니가 생성되도록 했고, 처음 생성되는 장바구니의 물품리스트에는 아무것도 담기지 않을거라 생각해서 Nullable을 지정해줬습니다.

2022-12-19 13:09 UTC, gnoesnooj commented on src/main/java/com/daily/gaboja/cart/dto/CartUpdateRequestDto.java
> +    private List<CartItem> cartItems;
null 허용시 장점으로는 우선 primitive와 wrapper를 생각해봤습니다. id 생성시에 wrapper 사용을 통해서 db가 id 생성을 하도록 맡길때 null을 사용하는 wrapper를 통해서 가능한 것으로 알고 있습니다.

단점으로는 null을 허용했기 때문에, 해당 칼럼을 가지고 어떤 연산이나 join을 행했을 때 문제가 있을 것 같습니다.

2022-12-19 13:09 UTC, gnoesnooj commented on src/main/java/com/daily/gaboja/cart/service/CartService.java
>          Cart cart = cartRepository.findById(cartUpdateRequestDto.getCartId()).orElseThrow(CartNotExistException::new);
^_^

2022-12-19 13:09 UTC, gnoesnooj commented on src/main/java/com/daily/gaboja/cart/service/CartService.java
>          Cart cart = cartRepository.findById(cartUpdateRequestDto.getCartId()).orElseThrow(CartNotExistException::new);
해당 장바구니를 찾고, 없다면 장바구니가 없다는 예외를 커스텀해서 throw 해주고 있습니다.

global exception handler는 아직 구현해주지 못했습니다 ㅠ

2022-12-19 13:10 UTC, gnoesnooj commented on src/main/java/com/daily/gaboja/cart/service/CartService.java
>          CartReadResponseDto cartReadResponseDto = new CartReadResponseDto();
^_^

2022-12-19 13:15 UTC, gnoesnooj commented on src/main/java/com/daily/gaboja/order/service/OrderService.java
> +    private final ProductValidator productValidator;
처음 productValidator 를 작성해줄 때, 장바구니를 주문으로 전환해줄때 해당 클래스의 validate 기능들을 적용해주어야 한다고 생각했고, 해당 기능들이 적용되어야 하는 부분은 서비스단에서 진행해주어야한다고 생각했습니다. 

검증에 대한 구분은...........

우선 서비스는 도메인 로직과 repository를 통해서 값을 처리하고 리턴해주기 때문에, 이러한 값에 대한 검증이 서비스검증의 역할인 것 같고,

컨트롤러는 처음 http method를 통해서 요청이 들어올 때, 그 요청 값들에 대한 검증을 진행해주는 역할을 한다고 생각합니다.

따라서 검증을 해주는 값에 따라서 두 레이어에서의 검증을 구분할 수 있을 것 같습니다.

2022-12-19 13:15 UTC, gnoesnooj commented on src/main/java/com/daily/gaboja/order/service/OrderService.java
> +        Cart cart = cartRepository.findById(orderRequestDto.getCartId()).orElseThrow(CartNotExistException::new);
ㅎ_ㅎ

2022-12-19 13:30 UTC, gnoesnooj commented on src/main/java/com/daily/gaboja/order/service/OrderService.java
>          Cart cart = cartRepository.findById(orderRequestDto.getCartId()).orElseThrow(CartNotExistException::new);
자세히 모르겠네용

하나의 트랜잭션일 때 발생하는 문제인가요 ?

2022-12-20 02:16 UTC, graygreat commented on src/main/java/com/daily/gaboja/cart/domain/Cart.java
>      @ElementCollection(fetch = FetchType.EAGER)
특징들을 알아보시고 말씀해주세요

2022-12-20 07:59 UTC, gnoesnooj commented on src/main/java/com/daily/gaboja/cart/domain/Cart.java
>      @ElementCollection(fetch = FetchType.EAGER)
eager 는 객체를 조회할 때, 연관된 객체 모두를 조회하는 특징을 가지고 있고, lazy는 우선 조회하는 객체만 가져온 후, 연관된 객체를 사용하는 시점에 조회를 하는 특징을 가지고 있습니다.

이러한 lazy의 특징 덕분에 eager의 '조회 시점에 모든 객체를 조회하기에 필요하지 않아도 select 쿼리가 나가는 n+1 문제가 발생할 수 있다는 단점'을 보완해준다고 알고 있습니다.

2022-12-20 08:05 UTC, gnoesnooj commented on src/main/java/com/daily/gaboja/cart/dto/CartReadResponseDto.java
>      public CartReadResponseDto toDto(Cart cart) {
네이밍 규칙이 있었네요

2022-12-27 02:26 UTC, graygreat approved these changes

2022-12-27 05:40 UTC, merged